### ISSUE TITLE
Get free stack space for Idle and timer RTX Thrads

### ISSUE THREAD

**Issue by juliobc** [ARM-software/CMSIS-RTX#49]
Hi,

How could I check the available space at runtime for osRtxIdleThread and osRtxTimerThread? I use watermark and I would like to monitor the available stack (the same as RTX RTOS window in debugger) so that I can raise an alarm if it falls below a limit to increase the stack. Is there any function in the API for that? if not, any workaround?

To use osThreadGetStackSpace(thread_id) I need the thread id (it is not accessible).

Thanks

**Comment by JonatanAntoni** [comment]
Hi @juliobc,

I've moved your question to the new home of RTX.

These thread IDs are not exposed via CMSIS-RTOS2 API because they are implementation specific. Thus, there is no generic implementation available. Nevertheless, if you access the RTX5 APIs directly, you could get the thread IDs of Idle and Timer threads from `osRtxInfo`.

The `osRtxInfo` struct is declared here:
https://github.com/ARM-software/CMSIS-RTX/blob/ce47c33e6919b6622f950099f059520e60424b12/Include/rtx_os.h#L354

It contains the member `idle` declared here:
https://github.com/ARM-software/CMSIS-RTX/blob/ce47c33e6919b6622f950099f059520e60424b12/Include/rtx_os.h#L306

And the member `timer.thread` declared here:
https://github.com/ARM-software/CMSIS-RTX/blob/ce47c33e6919b6622f950099f059520e60424b12/Include/rtx_os.h#L318

Cheers,
Jonatan

**Comment by juliobc** [comment]
Hi @JonatanAntoni 

perfect, thank you very much
